name: Master Workflow

env:
  DOCKER_AUTH_CONFIG: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - 'jvm'

jobs:
  main:
    name: Master Workflow Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: divloic/ccloud-registry-action@master
        with:
          avro-files-path: src/main/resources/
          avro-subject-yaml: src/main/resources/schemas.yaml
          schema-registry-url: ${{ secrets.SCHEMA_REGISTRY_URL }}
          schema-registry-api-key: ${{ secrets.SCHEMA_REGISTRY_API_KEY }}
          schema-registry-secret-key: ${{ secrets.SCHEMA_REGISTRY_SECRET_KEY }}
