name: Master Workflow

env:
  DOCKER_AUTH_CONFIG: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - 'jvm'

jobs:
  main:
    name: Master Workflow Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: divloic/ccloud-registry-action@preview
        with:
          avro-files-path: src/main/avro/
          avro-subject-yaml: src/main/avro/schemas.yaml
          schema-registry-url: ${{ secrets.SCHEMA-REGISTRY-URL }}
          schema-registry-api-key: ${{ secrets.SCHEMA-REGISTRY-API-KEY }}
          schema-registry-secret-key: ${{ secrets.SCHEMA-REGISTRY-SECRET-KEY }}
